version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v24.1.2
    pull_policy: if_not_present
    ports:
      - '26257:26257'
      - '8081:8080' #  --store=type=mem,size=0.25
    command: start-single-node --insecure --store=path=/cockroach/cockroach-data,size=30GB
    environment:
      - COCKROACH_USER=root
      - COCKROACH_PASSWORD=passwd
    volumes:
      - '${PWD}/cockroach/crdb:/cockroach/cockroach-data'
      - '${PWD}/cockroach/entrypoint:/docker-entrypoint-initdb.d'

volumes:
  cockroachdb:
